include:
  - board: seeed_xiao_ble
    shield: totem_left
  - board: seeed_xiao_ble
    shield: totem_right
  - board: seeed_xiao_ble
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeed_xiao_ble
    shield: settings_reset
